In [3]:
import torch
import torch.nn as nn
#定义数据
torch.manual_seed(100) #设置随机种子，以保证结果的可重复性。
predict = torch.rand(4, 5)
label = torch.tensor([4, 3, 3, 2])
print(predict)
print(label)

#定义交叉熵损失函数
criterion = nn.CrossEntropyLoss()

#计算整体的损失值
loss = criterion(predict, label)
print(loss)#最后将这四个样本的损失值进行求平均，得到整体的损失值。

#计算单个样本的损失值
one_loss = criterion(predict[0].unsqueeze(0), label[0].unsqueeze(0)) #.unsqueeze(0)是转二维向量
print(predict[0].unsqueeze(0), label[0].unsqueeze(0))


tensor([[0.1117, 0.8158, 0.2626, 0.4839, 0.6765],
        [0.7539, 0.2627, 0.0428, 0.2080, 0.1180],
        [0.1217, 0.7356, 0.7118, 0.7876, 0.4183],
        [0.9014, 0.9969, 0.7565, 0.2239, 0.3023]])
tensor([4, 3, 3, 2])
tensor(1.5230)
tensor([0.1117, 0.8158, 0.2626, 0.4839, 0.6765]) tensor(4)
